export type GinStyle="London Dry"|"Plymouth"|"Old Tom"|"Navy Strength"|"Contemporary"|"Barrel-Aged"|"Genever"|"Sloe Gin";
export type WineType=GinStyle;
export interface TopWineSeed{producer:string;name:string;wineType:GinStyle;region?:string;country?:string;}
const LD:GinStyle="London Dry";const P:GinStyle="Plymouth";const OT:GinStyle="Old Tom";const NS:GinStyle="Navy Strength";const C:GinStyle="Contemporary";const BA:GinStyle="Barrel-Aged";const G:GinStyle="Genever";const SG:GinStyle="Sloe Gin";
interface ProducerRow{producer:string;country?:string;wines:{name:string;type:GinStyle;region?:string}[];}
const CATALOG:ProducerRow[]=[
{producer:"Tanqueray",country:"UK",wines:[{name:"Tanqueray London Dry",type:LD,region:"Scotland"},{name:"Tanqueray No. Ten",type:C,region:"Scotland"},{name:"Tanqueray Rangpur",type:C,region:"Scotland"},{name:"Tanqueray Sevilla",type:C,region:"Scotland"}]},
{producer:"Beefeater",country:"UK",wines:[{name:"Beefeater London Dry",type:LD,region:"London"},{name:"Beefeater 24",type:C,region:"London"},{name:"Beefeater Blood Orange",type:C,region:"London"}]},
{producer:"Hendrick's",country:"UK",wines:[{name:"Hendrick's Gin",type:C,region:"Scotland"},{name:"Hendrick's Orbium",type:C,region:"Scotland"},{name:"Hendrick's Neptunia",type:C,region:"Scotland"},{name:"Hendrick's Lunar",type:C,region:"Scotland"}]},
{producer:"Bombay Sapphire",country:"UK",wines:[{name:"Bombay Sapphire",type:LD,region:"Hampshire"},{name:"Bombay Sapphire East",type:C,region:"Hampshire"},{name:"Star of Bombay",type:C,region:"Hampshire"}]},
{producer:"Gordon's",country:"UK",wines:[{name:"Gordon's London Dry",type:LD,region:"Scotland"},{name:"Gordon's Pink",type:C,region:"Scotland"},{name:"Gordon's Premium Pink",type:C,region:"Scotland"}]},
{producer:"Plymouth",country:"UK",wines:[{name:"Plymouth Gin",type:P,region:"Devon"},{name:"Plymouth Navy Strength",type:NS,region:"Devon"},{name:"Plymouth Sloe Gin",type:SG,region:"Devon"}]},
{producer:"Sipsmith",country:"UK",wines:[{name:"Sipsmith London Dry",type:LD,region:"London"},{name:"Sipsmith V.J.O.P.",type:NS,region:"London"},{name:"Sipsmith Lemon Drizzle",type:C,region:"London"},{name:"Sipsmith Sloe Gin",type:SG,region:"London"}]},
{producer:"The Botanist",country:"UK",wines:[{name:"The Botanist Islay Dry Gin",type:C,region:"Islay"}]},
{producer:"Monkey 47",country:"Germany",wines:[{name:"Monkey 47 Schwarzwald Dry Gin",type:C,region:"Black Forest"},{name:"Monkey 47 Sloe Gin",type:SG,region:"Black Forest"},{name:"Monkey 47 Distiller's Cut",type:C,region:"Black Forest"}]},
{producer:"Roku",country:"Japan",wines:[{name:"Roku Japanese Craft Gin",type:C,region:"Osaka"}]},
{producer:"Ki No Bi",country:"Japan",wines:[{name:"Ki No Bi Kyoto Dry Gin",type:C,region:"Kyoto"},{name:"Ki No Bi Sei",type:C,region:"Kyoto"},{name:"Ki No Bi Edition K",type:C,region:"Kyoto"}]},
{producer:"Nikka",country:"Japan",wines:[{name:"Nikka Coffey Gin",type:C,region:"Miyagi"}]},
{producer:"Aviation",country:"USA",wines:[{name:"Aviation American Gin",type:C,region:"Oregon"}]},
{producer:"St. George",country:"USA",wines:[{name:"St. George Terroir Gin",type:C,region:"California"},{name:"St. George Botanivore",type:C,region:"California"},{name:"St. George Dry Rye Gin",type:C,region:"California"}]},
{producer:"Ford's",country:"UK",wines:[{name:"Ford's Gin",type:LD,region:"London"},{name:"Ford's Officers' Reserve Navy Strength",type:NS,region:"London"}]},
{producer:"Hayman's",country:"UK",wines:[{name:"Hayman's London Dry",type:LD,region:"London"},{name:"Hayman's Old Tom",type:OT,region:"London"},{name:"Hayman's Royal Dock Navy Strength",type:NS,region:"London"},{name:"Hayman's Sloe Gin",type:SG,region:"London"}]},
{producer:"Bols",country:"Netherlands",wines:[{name:"Bols Genever",type:G,region:"Amsterdam"},{name:"Bols Barrel Aged Genever",type:BA,region:"Amsterdam"},{name:"Bols Corenwyn",type:G,region:"Amsterdam"}]},
{producer:"Nolet's",country:"Netherlands",wines:[{name:"Nolet's Silver Dry Gin",type:C,region:"Schiedam"},{name:"Nolet's Reserve Gin",type:C,region:"Schiedam"}]},
{producer:"Citadelle",country:"France",wines:[{name:"Citadelle Original",type:LD,region:"Cognac"},{name:"Citadelle Réserve",type:BA,region:"Cognac"},{name:"Citadelle No Mistake Old Tom",type:OT,region:"Cognac"}]},
{producer:"G'Vine",country:"France",wines:[{name:"G'Vine Floraison",type:C,region:"Cognac"},{name:"G'Vine Nouaison",type:C,region:"Cognac"}]},
{producer:"Drumshanbo",country:"Ireland",wines:[{name:"Drumshanbo Gunpowder Irish Gin",type:C,region:"Leitrim"}]},
{producer:"Dingle",country:"Ireland",wines:[{name:"Dingle Original Gin",type:C,region:"Kerry"}]},
{producer:"Malfy",country:"Italy",wines:[{name:"Malfy Originale",type:C,region:"Torino"},{name:"Malfy Con Limone",type:C,region:"Torino"},{name:"Malfy Rosa",type:C,region:"Torino"},{name:"Malfy Con Arancia",type:C,region:"Torino"}]},
{producer:"Gin Mare",country:"Spain",wines:[{name:"Gin Mare Mediterranean",type:C,region:"Barcelona"}]},
{producer:"Nordés",country:"Spain",wines:[{name:"Nordés Atlantic Galician Gin",type:C,region:"Galicia"}]},
{producer:"Whitley Neill",country:"UK",wines:[{name:"Whitley Neill Original",type:LD,region:"Birmingham"},{name:"Whitley Neill Rhubarb & Ginger",type:C,region:"Birmingham"},{name:"Whitley Neill Blood Orange",type:C,region:"Birmingham"},{name:"Whitley Neill Raspberry",type:C,region:"Birmingham"}]},
{producer:"Tarquin's",country:"UK",wines:[{name:"Tarquin's Cornish Dry Gin",type:LD,region:"Cornwall"},{name:"Tarquin's British Blackberry",type:C,region:"Cornwall"},{name:"Tarquin's Rhubarb & Raspberry",type:C,region:"Cornwall"}]},
{producer:"Edinburgh Gin",country:"UK",wines:[{name:"Edinburgh Gin Classic",type:LD,region:"Edinburgh"},{name:"Edinburgh Gin Seaside",type:C,region:"Edinburgh"},{name:"Edinburgh Gin Rhubarb & Ginger",type:C,region:"Edinburgh"}]},
{producer:"Portobello Road",country:"UK",wines:[{name:"Portobello Road No. 171",type:LD,region:"London"},{name:"Portobello Road Navy Strength",type:NS,region:"London"}]},
{producer:"City of London",country:"UK",wines:[{name:"City of London Dry Gin",type:LD,region:"London"},{name:"City of London Christopher Wren",type:C,region:"London"}]},
{producer:"Oxley",country:"UK",wines:[{name:"Oxley Cold Distilled London Dry",type:LD,region:"London"}]},
{producer:"Four Pillars",country:"Australia",wines:[{name:"Four Pillars Rare Dry Gin",type:C,region:"Yarra Valley"},{name:"Four Pillars Navy Strength",type:NS,region:"Yarra Valley"},{name:"Four Pillars Bloody Shiraz",type:C,region:"Yarra Valley"},{name:"Four Pillars Olive Leaf",type:C,region:"Yarra Valley"}]},
{producer:"Never Never",country:"Australia",wines:[{name:"Never Never Triple Juniper",type:LD,region:"Adelaide Hills"},{name:"Never Never Southern Strength",type:NS,region:"Adelaide Hills"}]},
{producer:"Archie Rose",country:"Australia",wines:[{name:"Archie Rose Signature Dry Gin",type:C,region:"Sydney"},{name:"Archie Rose Distiller's Strength",type:NS,region:"Sydney"}]},
{producer:"Fever-Tree",country:"UK",wines:[{name:"Fever-Tree Premium Indian Tonic Water",type:LD,region:"London"}]},
{producer:"Uncle Val's",country:"USA",wines:[{name:"Uncle Val's Botanical Gin",type:C,region:"Oregon"},{name:"Uncle Val's Peppered Gin",type:C,region:"Oregon"}]},
{producer:"Barr Hill",country:"USA",wines:[{name:"Barr Hill Gin",type:C,region:"Vermont"},{name:"Barr Hill Tom Cat Barrel-Aged",type:BA,region:"Vermont"}]},
{producer:"Gray Whale",country:"USA",wines:[{name:"Gray Whale Gin",type:C,region:"California"}]},
{producer:"Empress 1908",country:"Canada",wines:[{name:"Empress 1908 Gin",type:C,region:"Victoria"}]},
{producer:"The Bluecoat",country:"USA",wines:[{name:"Bluecoat American Dry Gin",type:C,region:"Philadelphia"}]},
{producer:"Death's Door",country:"USA",wines:[{name:"Death's Door Gin",type:C,region:"Wisconsin"}]},
{producer:"Junipero",country:"USA",wines:[{name:"Junipero Gin",type:LD,region:"San Francisco"}]},
{producer:"Perry's Tot",country:"USA",wines:[{name:"Perry's Tot Navy Strength",type:NS,region:"Brooklyn"}]},
{producer:"Dorothy Parker",country:"USA",wines:[{name:"Dorothy Parker Gin",type:C,region:"Brooklyn"}]},
{producer:"Greenhook",country:"USA",wines:[{name:"Greenhook American Dry Gin",type:LD,region:"Brooklyn"},{name:"Greenhook Old Tom",type:OT,region:"Brooklyn"}]},
];
export const topWines:TopWineSeed[]=CATALOG.flatMap(row=>row.wines.map(w=>({producer:row.producer,name:w.name,wineType:w.type,region:w.region,country:row.country})));
export const TOP_COUNT=topWines.length;
